### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by zrzyyds** [zhengqigao/BayesOpt-JLT2022#1]
Dr. Gao
hello！I'm very interested in this work of yours. I tried running the code but got some errors and I don't know how to fix them.

![Screenshot from 2023-09-12 14-54-13](https://github.com/zhengqigao/BayesOpt-JLT2022/assets/82270914/61cfdcbe-ebba-44f8-b761-9b99c9e2a7bf)
![Screenshot from 2023-09-12 14-54-37](https://github.com/zhengqigao/BayesOpt-JLT2022/assets/82270914/848bd337-c1a6-4c69-a5d1-e69a2ee66ad1)

I currently set up a conda virtual environment for this purpose and loaded some necessary function libraries. The python version is 3.10.

**Comment by zhengqigao** [comment]
Hi, 

The first error implies that Lumerical FDTD simulation command is not found. `fdtd-solutions` is the command to run an FDTD simulation in terminal, [See here](https://optics.ansys.com/hc/en-us/articles/360024974033-Running-simulations-using-terminal-in-Linux). I would suggest first directly typing `fdtd-solutions` in a terminal to see if Lumerical FDTD could start successfully.

The second error implies the simulation result file is not found. This `sim_res.txt` file is generated by the lsf script (simulation script) and is parsed by Python script. It is possible because your `fdtd-solution` is not installed and thus simulation doesn't run, so no simulation results are stored.

**Comment by zrzyyds** [comment]
Dr. Gao
thank you for your reply. The above error has been resolved and the program runs perfectly.
